######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 4 09:45:35 2009
######################################################################

TEMPLATE = app
TARGET = ../server
DEPENDPATH += .
INCLUDEPATH += .
# Input
HEADERS += src/server/AbstractServer.h src/server/SingleThreadServer.h src/game/GameHost.h src/game/PokerRoomListener.h src/game/AbstractPokerGame.h src/game/TexasHoldemPokerGame.h src/model/game_engine/AbstractCardsDeckModel.h src/model/game_engine/CardModel.h src/game/AuctionAction.h
SOURCES += src/Main.cpp src/server/AbstractServer.cpp src/server/SingleThreadServer.cpp src/game/GameHost.cpp src/game/PokerRoomListener.cpp src/game/AbstractPokerGame.cpp src/game/TexasHoldemPokerGame.cpp src/model/game_engine/CardModel.cpp src/model/game_engine/AbstractCardsDeckModel.cpp src/game/AuctionAction.cpp

# MODELS
HEADERS += src/model/server/PokerRoomModel.h src/model/server/PokerHostModel.h src/model/server/MsvClientMessage.h src/model/server/JoinTableInfoModel.h src/model/server/PokerPlayerModel.h src/model/server/AuthInfoModel.h src/model/server/GameActionModel.h src/model/server/BetModel.h src/model/game_engine/GamePlayerModel.h src/model/game_engine/SimpleFiftyTwoCardsDeckModel.h src/model/game_engine/GameBankModel.h src/model/server/MessagePool.h src/model/server/JoinChairInfoModel.h src/model/game_engine/AuctionPlayerModel.h
SOURCES += src/model/server/PokerRoomModel.cpp src/model/server/PokerHostModel.cpp  src/model/server/MsvClientMessage.cpp src/model/server/JoinTableInfoModel.cpp src/model/server/PokerPlayerModel.cpp src/model/server/AuthInfoModel.cpp src/model/server/GameActionModel.cpp src/model/server/BetModel.cpp src/model/game_engine/GamePlayerModel.cpp src/model/game_engine/SimpleFiftyTwoCardsDeckModel.cpp src/model/game_engine/GameBankModel.cpp src/model/server/MessagePool.cpp src/model/server/JoinChairInfoModel.cpp src/model/game_engine/AuctionPlayerModel.cpp
#

# UTILS
HEADERS += src/utils/ConfigReaderUtil.h src/utils/MessageTransformer.h src/service/AuthenticationService.h src/utils/MessageBuilder.h src/utils/PokerGameHelper.h src/utils/XmlParserHelper.h src/utils/MessageSenderUtil.h src/utils/StringUtil.h
SOURCES += src/utils/ConfigReaderUtil.cpp src/utils/MessageTransformer.cpp src/service/AuthenticationService.cpp src/utils/MessageBuilder.cpp src/utils/PokerGameHelper.cpp src/utils/XmlParserHelper.cpp src/utils/MessageSenderUtil.cpp src/utils/StringUtil.cpp
#

QT += network
QT += xml
CONFIG += console
RESOURCES += application.qrc
