######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 4 09:45:35 2009
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .
# Input
HEADERS += src/server/AbstractServer.h src/server/SingleThreadServer.h src/game/GameHost.h src/game/PokerRoomListener.h src/game/AbstractPokerGame.h src/game/TexasHoldemPokerGame.h src/model/game_engine/AbstractCardsDeckModel.h src/model/game_engine/CardModel.h src/game/PokerPlayerListener.h
SOURCES += src/Test.cpp src/server/AbstractServer.cpp src/server/SingleThreadServer.cpp src/game/GameHost.cpp src/game/PokerRoomListener.cpp src/game/AbstractPokerGame.cpp src/game/TexasHoldemPokerGame.cpp src/model/game_engine/CardModel.cpp src/model/game_engine/AbstractCardsDeckModel.cpp src/game/PokerPlayerListener.cpp

# MODELS
HEADERS += src/model/server/PokerRoomModel.h src/model/server/PokerHostModel.h src/model/server/MsvClientMessage.h src/model/server/JoinTableInfoModel.h src/model/server/PokerPlayerModel.h src/model/server/AuthInfoModel.h src/model/server/GameActionModel.h src/model/server/BetModel.h src/model/game_engine/SimpleFiftyTwoCardsDeckModel.h src/model/game_engine/GamePlayerModel.h src/model/game_engine/GameBankModel.h src/model/server/RoomMessagePool.h src/model/server/JoinChairInfoModel.h
SOURCES += src/model/server/PokerRoomModel.cpp src/model/server/PokerHostModel.cpp  src/model/server/MsvClientMessage.cpp src/model/server/JoinTableInfoModel.cpp src/model/server/PokerPlayerModel.cpp src/model/server/AuthInfoModel.cpp src/model/server/GameActionModel.cpp src/model/server/BetModel.cpp src/model/game_engine/SimpleFiftyTwoCardsDeckModel.cpp src/model/game_engine/GamePlayerModel.cpp src/model/game_engine/GameBankModel.cpp src/model/server/RoomMessagePool.cpp src/model/server/JoinChairInfoModel.cpp
#

# UTILS
HEADERS += src/utils/ConfigReaderUtil.h src/utils/MessageTransformer.h src/service/AuthenticationService.h src/utils/MessageBuilder.h src/utils/PokerGameHelper.h 
SOURCES += src/utils/ConfigReaderUtil.cpp src/utils/MessageTransformer.cpp src/service/AuthenticationService.cpp src/utils/MessageBuilder.cpp src/utils/PokerGameHelper.cpp
#

#TESTS
HEADERS += src/tests/service/Test_AuthenticationService.h src/tests/model/game_engine/Test_SimpleFiftyTwoCardsDeckModel.h src/tests/game/Test_TexasHoldemPokerGame.h src/tests/utils/Test_PokerGameHelper.h src/tests/utils/Test_MessageTransformer.h src/tests/utils/Test_ConfigReaderUtil.h src/utils/XmlParserHelper.h
SOURCES += src/tests/service/Test_AuthenticationService.cpp src/tests/model/game_engine/Test_SimpleFiftyTwoCardsDeckModel.cpp src/tests/game/Test_TexasHoldemPokerGame.cpp  src/tests/utils/Test_PokerGameHelper.cpp src/tests/utils/Test_MessageTransformer.cpp src/tests/utils/Test_ConfigReaderUtil.cpp src/utils/XmlParserHelper.cpp

QT += network
QT += xml
CONFIG += console
CONFIG += qtestlib
TARGET = ../QTests
RESOURCES += application.qrc

